### ISSUE TITLE
Invalid Json Response

### ISSUE THREAD

**Issue by chashmeetsingh** [brunoadacosta/lomadee#1]
The gem is returning an invalid json format which needs to be fixed so that parsing of the json is simple

**Comment by brunoadacosta** [comment]
@chashmeetsingh have an example?

**Comment by chashmeetsingh** [comment]
Invalid JSON

{"details"=>{"applicationID"=>"47666456366c3141776f773d", "applicationVersion"=>"1.0", "applicationPath"=>nil, "date"=>"2015-09-29T13:50:45.812-03:00", "elapsedTime"=>"23", "status"=>"success", "code"=>"0", "message"=>"success"}, "category"=>{"thumbnail"=>{"url"=>"http://imagem.buscape.com.br/bp5/categorias/6424.jpg"}, "links"=>{"link"=>[{"url"=>"http://www.buscape.com.br/notebook.html?mdsrc=9262544&mdapp=7327&mddtn=51922611", "type"=>"category"}, {"url"=>"http://sandbox.buscape.com.br/service/findProductList/lomadee/47666456366c3141776f773d/br/?categoryId=6424&keyword=apple&sourceId=9262544", "type"=>"xml"}]}, "name"=>"Notebook", "id"=>"6424", "parentCategoryId"=>"2", "isFinal"=>"true", "hasOffer"=>"false", "concatenateCategoryName"=>"false"}, "product"=>[{"productName"=>"Apple Macbook Pro MD101BZ Intel Core i5 2.5 GHz 4096 MB 500 GB", "productShortName"=>"Notebook Apple Macbook Pro MD101BZ", "currency"=>{"abbreviation"=>"BRL"}, "priceMin"=>"5193.02", "priceMax"=>"6399.00", "links"=>{"link"=>[{"url"=>"http://www.buscape.com.br/prod_unico?idu=407999&mdsrc=9262544&mdapp=7327&mddtn=51922611", "type"=>"product"}, {"url"=>"http://sandbox.buscape.com.br/service/findOfferList/lomadee/47666456366c3141776f773d/br/?productId=407999&keyword=apple&sourceId=9262544", "type"=>"xml"}]}, "thumbnail"=>{"formats"=>[{"url"=>"http://thumbs.buscape.com.br/notebook/apple-macbook-pro-md101bz-intel-core-i5-2-5-ghz-4096-mb-500-gb_100x100-PU639bf_1.jpg", "height"=>"100", "width"=>"100"}, {"url"=>"http://thumbs.buscape.com.br/notebook/apple-macbook-pro-md101bz-intel-core-i5-2-5-ghz-4096-mb-500-gb_300x300-PU639bf_1.jpg", "height"=>"300", "width"=>"300"}, {"url"=>"http://thumbs.buscape.com.br/notebook/apple-macbook-pro-md101bz-intel-core-i5-2-5-ghz-4096-mb-500-gb_600x600-PU639bf_1.jpg", "height"=>"600", "width"=>"600"}], "url"=>"http://thumbs.buscape.com.br/notebook/apple-macbook-pro-md101bz-intel-core-i5-2-5-ghz-4096-mb-500-gb_200x200-PU639bf_1.jpg", "height"=>"200", "width"=>"200"}, "rating"=>{"userAverageRating"=>{"numComments"=>"156", "rating"=>"9.0", "links"=>{"link"=>{"url"=>"http://sandbox.buscape.com.br/service/viewUserRatings/47666456366c3141776f773d/br/?productId=407999&keyword=apple&sourceId=9262544", "type"=>"xml"}}}}, "specification"=>{"links"=>

Valid JSON

{"details":{"applicationID":"47666456366c3141776f773d", "applicationVersion":"1.0", "applicationPath":"nil", "date":"2015-09-29T13:52:53.721-03:00", "elapsedTime":"23", "status":"success", "code":"0", "message":"success"}, "category":{"thumbnail":{"url":"http://imagem.buscape.com.br/bp5/categorias/6424.jpg"}, "links":{"link":[{"url":"http://www.buscape.com.br/notebook.html?mdsrc=9262544&mdapp=7327&mddtn=51922611", "type":"category"}, {"url":"http://sandbox.buscape.com.br/service/findProductList/lomadee/47666456366c3141776f773d/br/?categoryId=6424&keyword=apple&sourceId=9262544", "type":"xml"}]}, "name":"Notebook", "id":"6424", "parentCategoryId":"2", "isFinal":"true", "hasOffer":"false", "concatenateCategoryName":"false"}, "product":[{"productName":"Apple Macbook Pro MD101BZ Intel Core i5 2.5 GHz 4096 MB 500 GB", "productShortName":"Notebook Apple Macbook Pro MD101BZ", "currency":{"abbreviation":"BRL"}, "priceMin":"5193.02", "priceMax":"6399.00", "links":{"link":[{"url":"http://www.buscape.com.br/prod_unico?idu=407999&mdsrc=9262544&mdapp=7327&mddtn=51922611", "type":"product"}, {"url":"http://sandbox.buscape.com.br/service/findOfferList/lomadee/47666456366c3141776f773d/br/?productId=407999&keyword=apple&sourceId=9262544", "type":"xml"}]}, "thumbnail":{"formats":[{"url":"http://thumbs.buscape.com.br/notebook/apple-macbook-pro-md101bz-intel-core-i5-2-5-ghz-4096-mb-500-gb_100x100-PU639bf_1.jpg", "height":"100", "width":"100"}, {"url":"http://thumbs.buscape.com.br/notebook/apple-macbook-pro-md101bz-intel-core-i5-2-5-ghz-4096-mb-500-gb_300x300-PU639bf_1.jpg", "height":"300", "width":"300"}, {"url":"http://thumbs.buscape.com.br/notebook/apple-macbook-pro-md101bz-intel-core-i5-2-5-ghz-4096-mb-500-gb_600x600-PU639bf_1.jpg", "height":"600", "width":"600"}], "url":"http://thumbs.buscape.com.br/notebook/apple-macbook-pro-md101bz-intel-core-i5-2-5-ghz-4096-mb-500-gb_200x200-PU639bf_1.jpg", "height":"200", "width":"200"}, "rating":{"userAverageRating":{"numComments":"156", "rating":"9.0", "links":{"link":{"url":"http://sandbox.buscape.com.br/service/viewUserRatings/47666456366c3141776f773d/br/?productId=407999&keyword=apple&sourceId=9262544", "type":"xml"}}}}, "specification":{"links":{"link":{"url":"http://sandbox.buscape.com.br/service/viewProductDetails/47666456366c3141776f773d/br/?productId=407999&keyword=apple&sourceId=9262544", "type":"xml"}}, "item":[{"value":"13.3 polegadas", "label":"Tela"}, {"value":"Intel HD Graphics", "label":"Placa de vídeo"}, {"value":"3 Porta(s)", "label":"Entrada USB"}, {"value":"Sim", "label":"Web Cam"}, {"value":"Mac OS", "label":"Sistema Operacional"}]}, "fullDescription":"false", "totalSellers":"8", "categoryId":"6424", "hasMetaSearch":"false", "eco":"false", "id":"407999", "quantity":"0", "numOffers":"10"}, {"productName":"Apple Macbook Pro MF839 Intel Core i5 2.7 GHz 8192 MB 128 GB", "productShortName":"Notebook Apple Macbook Pro MF839", "currency":{"abbreviation":"BRL"}, "priceMin":"7054.20", "priceMax":"8499.00"

Just replace '=>' with ':' also nil within ""

**Comment by brunoadacosta** [comment]
@chashmeetsingh the return is a ruby hash, if you want a json, use https://github.com/ohler55/oj 
`Oj.dump lomadee_return`

**Comment by chashmeetsingh** [comment]
can u also provide data in different formats like json , xml ,etc
